package ru.jts_dev.gameserver.constants;

/**
 * @author Camelion
 * @since 20.01.16
 */
public enum ActionHandlerType {
    WALK_RUN, ATTACK, TRADE, CLIENT_ACTION, PRIVATE_STORE, PACKAGE_PRIVATE_STORE, SOCIAL_ACTION, PET_ACTION, PET_DEPOSIT, SUMMON_ACTION, SUMMON_DESPAWN, PRIVATE_BUY, MAKE_ITEM, MAKE_ITEM2, RIDE, TELEPORT_BOOKMARK, BOT_REPORT, AIRSHIP_ACTION, COUPLE_ACTION, SIT_STAND
}
