package ru.jts_dev.gameserver.constants;

/**
 * @author Camelion
 * @since 07.01.16
 */
public enum DefaultAction {
    ACTION_NONE,
    ACTION_EQUIP,
    ACTION_PEEL,
    ACTION_SKILL_REDUCE,
    ACTION_SOULSHOT,
    ACTION_RECIPE,
    ACTION_SKILL_MAINTAIN,
    ACTION_SPIRITSHOT,
    ACTION_DICE,
    ACTION_CALC,
    ACTION_SEED,
    ACTION_HARVEST,
    ACTION_CAPSULE,
    ACTION_XMAS_OPEN,
    ACTION_SHOW_HTML,
    ACTION_SHOW_SSQ_STATUS,
    ACTION_FISHINGSHOT,
    ACTION_SUMMON_SOULSHOT,
    ACTION_SUMMON_SPIRITSHOT,
    ACTION_CALL_SKILL,
    ACTION_SHOW_ADVENTURER_GUIDE_BOOK,
    ACTION_KEEP_EXP,
    ACTION_CREATE_MPCC,
    ACTION_NICK_COLOR,
    ACTION_HIDE_NAME,
    ACTION_START_QUEST
}
