package ru.jts_dev.gameserver.constants;

/**
 * @author Camelion
 * @since 16.02.16
 */
public enum NpcType {
    WARRIOR, BOSS, ZZOLDAGU, CITIZEN, TREASURE, WORLD_TRAP, MERCHANT, GUARD, GUILD_MASTER, WAREHOUSE_KEEPER, TELEPORTER,
    GUILD_COACH, BLACKSMITH, MONRACE, MRKEEPER, PACKAGE_KEEPER, HOLYTHING, SIEGE_ATTACKER, OWNTHING, SUMMON, PET,
    XMASTREE, PC_TRAP, DOPPELGANGER
}
